### ISSUE TITLE
Where is the part "Creating questions" ? Why did not you see it in this code?

### ISSUE THREAD

**Issue by tcxia** [KristiyanVachev/Question-Generation#1]

**Comment by KristiyanVachev** [comment]
I didn't have enough time to write the code for it at the time. But since this repo is starting to get some attention I'm planning to do it and also refactor the rest of the code.

**Comment by pidugusundeep** [comment]
@MarsTT Hey I was using this for answer generation/important keywords extraction and you could use [question-generation](https://github.com/bloomsburyai/question-generation) and combine them both to generate question just by passing the document text and generated keywords 
[Label Answers.ipynb](https://github.com/KristiyanVachev/Question-Generation/blob/master/04.%20Label%20answers/Label%20Answers.ipynb)
```python
for i in range(len(y_pred)):
    if (y_pred[i]):   
        print('T', df.iloc[i]['text'])
    else:
        print('F', df.iloc[i]['text'])
```

**Comment by KristiyanVachev** [comment]
Hey @MarsTT , I've finally added *[Demo.ipynb](https://github.com/KristiyanVachev/Question-Generation/blob/master/Demo.ipynb)* which puts together all the components and generates questions from any text :)
