### ISSUE TITLE
Proper Documentation needed.

### ISSUE THREAD

**Issue by tirtharajghosh** [KristiyanVachev/Question-Generation#12]
A proper documentation is needed to execute this project. What are the requirements? How should one execute ?

**Comment by parthpanchal3399** [comment]
Hello, 
Even I had faced the same problem. However I managed to get it working somehow.
requirements:
gensim
spacy
pandas
nltk

(if after running you get any errors with Module not found, then install it with pip)

You only need to files
Demo.ipynb
data/

in the data/ folder, download and place the files according to the readme here https://github.com/KristiyanVachev/Question-Generation/blob/master/data/README.md

Do not change anything and run the Demo.ipynb

PS: You might face a Value error. Make sure the input doesnt have words "like" ,"despite"

**Comment by KristiyanVachev** [comment]
I agree! I am going to add instructions for creating a virtual environment and a requirements.txt file. Is there anything else documentation-wise you would like to exist, @tirtharajghosh?

@parthpanchal3399 sorry for you having to figure this out on your own. Thank you for putting in so much effort into my repo!

**Comment by tirtharajghosh** [comment]
@KristiyanVachev I think the requirements.txt and mentioning the Demo.ipynb as the starting point would be more than enough.

**Comment by parthpanchal3399** [comment]
@KristiyanVachev Not a problem. Good to know you'll be adding further documentation. 
Also would you please look into the issue I've opened?

Thanks.

**Comment by KristiyanVachev** [comment]
> @KristiyanVachev Not a problem. Good to know you'll be adding further documentation.
> Also would you please look into the issue I've opened?
> 
> Thanks.

Yes. I will look into the annoying "ValueError: operands could not be broadcast together with shapes (230, 121) (83, )" problem that a loft of people seem to have. (I think I remember what the issues was - I think the difference between the one-hot encoded POS and DEP tags of the train and test samples) and the other issues as well. I just have to finish a few other deadlines first.

**Comment by KristiyanVachev** [comment]
I added a requirements.txt along with instructions how to run it, including the creation of a virtual environment .
