### ISSUE TITLE
Is there any configuration where i could change the answer length

### ISSUE THREAD

**Issue by pidugusundeep** [KristiyanVachev/Question-Generation#2]
Is there any configuration to change the n-gram length of the answer? as the words generated are not that great.

**Comment by KristiyanVachev** [comment]
Sorry, the repo was a university project and I didn't spend time on configurations or on n-grams longer than a single word.

**Comment by sirius0503** [comment]
@KristiyanVachev : I have a sentence such as 

> A site is your own private website

There are no named entities discovered through spacy's NER here and the fill in the blanks type question that I wish to make would be something like **A site is your own _____**, with *private website* as the answer, for which I was thinking of using only the pos tags, dependency, shape ,etc but here while I can get the token of **private website** using n-grams, but these wouldn't then have `pos tags`, `dependency`, and only shape. 

It'd be really helpful, if you could help out here with any ideas on how to handle such an issue, thanks

**Comment by KristiyanVachev** [comment]
> @KristiyanVachev : I have a sentence such as
> 
> > A site is your own private website
> 
> There are no named entities discovered through spacy's NER here and the fill in the blanks type question that I wish to make would be something like **A site is your own _____**, with _private website_ as the answer, for which I was thinking of using only the pos tags, dependency, shape ,etc but here while I can get the token of **private website** using n-grams, but these wouldn't then have `pos tags`, `dependency`, and only shape.
> 
> It'd be really helpful, if you could help out here with any ideas on how to handle such an issue, thanks

Sorry for the late answer. An approach for dealing with the token-specific tags for n-grams would be to simply combine the two (or n) tags into one. In your case making a new tag of ADJ-NOUN. Tough this would create a more sparse dataset which would be harder for the algorithm to deal with. 
My approach would be to out of the two POS tags to just take the dominant for the combined two words. In this case, just assign it as NOUN.
