### ISSUE TITLE
Cannot find a the main file, that implements all your components.

### ISSUE THREAD

**Issue by tech2date** [KristiyanVachev/Question-Generation#4]
I think the approach used is great, but i cannot find a file that implements all other files, can you please upload that. What else is missing in the project?

**Comment by KristiyanVachev** [comment]
Yeah, sorry about that. 
It's under construction. I just have to find the spare time to finish and upload it :)

**Comment by KristiyanVachev** [comment]
I've added a couple more functions and put it all together for a cool demo in *Demo.ipynb* :)

**Comment by caudurodev** [comment]
Good stuff! But I just tried your notebook and it has a missing file in the demo in the repo:
FileNotFoundError: [Errno 2] No such file or directory: 'data/embeddings/glove.6B.300d.txt'

**Comment by KristiyanVachev** [comment]
> Good stuff! But I just tried your notebook and it has a missing file in the demo in the repo:
> FileNotFoundError: [Errno 2] No such file or directory: 'data/embeddings/glove.6B.300d.txt'

You must download the files yourself. They are quite heavy and I don't think I have a license to upload them. There are README files with links and instructions in /data folder.

**Comment by caudurodev** [comment]
OK thanks - did not see that.
